import { BackGroundLayer } from "./background";
import { BackColorLayer } from "./backcolor";
import {
  RasterTileLayer,
  RasterLayerType,
  RasterTileStyle,
  defaultRasterTileStyle,
  RasterTileLayout,
  defaultRasterTileLayout,
} from "./rastertile";
import { VectorTileLayer } from "./vectortile";
import { GeoJsonLayer } from "./geojson";
import {
  IgsLayerType,
  IgsLayerTypeDefine,
  IgsDocLayer,
  IgsWmsLayer,
} from "./igserver";

import {
  defaultId,
  LayerType,
  LayerDefine,
  ILayer,
  IInfo,
  IStyle,
  IFilter,
  ILayout,
  changeLayerProperty,
  getLayerById,
  changeLayerName,
  changeLayerId,
  checkLayerVisible,
  changeLayersVisible,
  compareLayers,
} from "./baselayer";

export {
  BackGroundLayer,
  BackColorLayer,
  RasterTileLayer,
  RasterLayerType,
  RasterTileStyle,
  defaultRasterTileStyle,
  RasterTileLayout,
  defaultRasterTileLayout,
  VectorTileLayer,
  GeoJsonLayer,
  IgsLayerType,
  IgsLayerTypeDefine,
  IgsDocLayer,
  IgsWmsLayer,
  defaultId,
  LayerType,
  LayerDefine,
  ILayer,
  IInfo,
  IStyle,
  IFilter,
  ILayout,
  changeLayerProperty,
  getLayerById,
  changeLayerName,
  changeLayerId,
  checkLayerVisible,
  changeLayersVisible,
  compareLayers,
};

export default {
  BackGroundLayer,
  BackColorLayer,
  RasterTileLayer,
  RasterLayerType,
  RasterTileStyle,
  defaultRasterTileStyle,
  RasterTileLayout,
  defaultRasterTileLayout,
  VectorTileLayer,
  GeoJsonLayer,

  IgsLayerType,
  IgsLayerTypeDefine,
  IgsDocLayer,
  IgsWmsLayer,

  defaultId,
  LayerType,
  LayerDefine,
  ILayer,
  IInfo,
  IStyle,
  IFilter,
  ILayout,
  changeLayerProperty,
  getLayerById,
  changeLayerName,
  changeLayerId,
  checkLayerVisible,
  changeLayersVisible,
  compareLayers,
};
